
//此源码被清华学神尹成大魔王专业翻译分析并修改
//尹成QQ77025077
//尹成微信18510341407
//尹成所在QQ群721929980
//尹成邮箱 yinc13@mails.tsinghua.edu.cn
//尹成毕业于清华大学,微软区块链领域全球最有价值专家
//https://mvp.microsoft.com/zh-cn/PublicProfile/4033620
//Code generated by mockery v1.0.0. 不要编辑。

package mocks

import mock "github.com/stretchr/testify/mock"
import transientstore "github.com/hyperledger/fabric/core/transientstore"

//rwsetscanner是为rwsetscanner类型自动生成的模拟类型
type RWSetScanner struct {
	mock.Mock
}

//close为给定字段提供模拟函数：
func (_m *RWSetScanner) Close() {
	_m.Called()
}

//接下来提供一个具有给定字段的模拟函数：
func (_m *RWSetScanner) Next() (*transientstore.EndorserPvtSimulationResults, error) {
	ret := _m.Called()

	var r0 *transientstore.EndorserPvtSimulationResults
	if rf, ok := ret.Get(0).(func() *transientstore.EndorserPvtSimulationResults); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transientstore.EndorserPvtSimulationResults)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

//NextWithConfig提供了一个具有给定字段的模拟函数：
func (_m *RWSetScanner) NextWithConfig() (*transientstore.EndorserPvtSimulationResultsWithConfig, error) {
	ret := _m.Called()

	var r0 *transientstore.EndorserPvtSimulationResultsWithConfig
	if rf, ok := ret.Get(0).(func() *transientstore.EndorserPvtSimulationResultsWithConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transientstore.EndorserPvtSimulationResultsWithConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
