
//此源码被清华学神尹成大魔王专业翻译分析并修改
//尹成QQ77025077
//尹成微信18510341407
//尹成所在QQ群721929980
//尹成邮箱 yinc13@mails.tsinghua.edu.cn
//尹成毕业于清华大学,微软区块链领域全球最有价值专家
//https://mvp.microsoft.com/zh-cn/PublicProfile/4033620
//Code generated by mockery v1.0.0. 不要编辑。
package mocks

import chaincode "github.com/hyperledger/fabric/common/chaincode"
import mock "github.com/stretchr/testify/mock"

//枚举器是为枚举器类型自动生成的模拟类型
type Enumerator struct {
	mock.Mock
}

//枚举提供具有给定字段的模拟函数：
func (_m *Enumerator) Enumerate() ([]chaincode.InstalledChaincode, error) {
	ret := _m.Called()

	var r0 []chaincode.InstalledChaincode
	if rf, ok := ret.Get(0).(func() []chaincode.InstalledChaincode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chaincode.InstalledChaincode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
