
//此源码被清华学神尹成大魔王专业翻译分析并修改
//尹成QQ77025077
//尹成微信18510341407
//尹成所在QQ群721929980
//尹成邮箱 yinc13@mails.tsinghua.edu.cn
//尹成毕业于清华大学,微软区块链领域全球最有价值专家
//https://mvp.microsoft.com/zh-cn/PublicProfile/4033620
//Code generated by mockery v1.0.0. 不要编辑。
package mocks

import api "github.com/hyperledger/fabric/gossip/api"
import mock "github.com/stretchr/testify/mock"

//SecurityAdvisor是SecurityAdvisor类型的自动生成的模拟类型
type SecurityAdvisor struct {
	mock.Mock
}

//orgbypeerIdentity提供了一个具有给定字段的模拟函数：a0
func (_m *SecurityAdvisor) OrgByPeerIdentity(_a0 api.PeerIdentityType) api.OrgIdentityType {
	ret := _m.Called(_a0)

	var r0 api.OrgIdentityType
	if rf, ok := ret.Get(0).(func(api.PeerIdentityType) api.OrgIdentityType); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.OrgIdentityType)
		}
	}

	return r0
}
