
//此源码被清华学神尹成大魔王专业翻译分析并修改
//尹成QQ77025077
//尹成微信18510341407
//尹成所在QQ群721929980
//尹成邮箱 yinc13@mails.tsinghua.edu.cn
//尹成毕业于清华大学,微软区块链领域全球最有价值专家
//https://mvp.microsoft.com/zh-cn/PublicProfile/4033620
//Code generated by mockery v1.0.0. 不要编辑。

package mocks

import cluster "github.com/hyperledger/fabric/orderer/common/cluster"

import mock "github.com/stretchr/testify/mock"

//配置器是为配置器类型自动生成的模拟类型
type Configurator struct {
	mock.Mock
}

//configure提供了一个具有给定字段的模拟函数：channel、newnodes
func (_m *Configurator) Configure(channel string, newNodes []cluster.RemoteNode) {
	_m.Called(channel, newNodes)
}
